apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitex-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitex-app
  template:
    metadata:
      labels:
        app: gitex-app
    spec:
      containers:
      - name: gitex-app
        image: ghcr.io/kimberlee-sgcm/gitex-workshop/gitex-workshop-f79fa0363b1c51659713a33d69e513bd@sha256:da097c0432978e134ba60b36c2a699592219b61e9e86c386927ed4fd9ac34389
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gitex-service
  namespace: default
spec:
  selector:
    app: gitex-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitex-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: gitex-demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitex-service
            port:
              number: 80
